[build]
builder = "nixpacks"
buildCommand = "PRISMA_CLI_QUERY_ENGINE_TYPE=binary npx prisma generate && npm run build"

[deploy]
startCommand = "PRISMA_CLI_QUERY_ENGINE_TYPE=binary npx prisma db push --force-reset && npm run start:prod"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
