[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx prisma db push --force-reset && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
